/**
 * @wireframe-skill multi-screen-wireframe@2.1.0
 * 创建基于 v2.0.0
 * 修改基于 v2.1.0
 */
WireframeVue.defineScreen('history', () => ({
  setup() { return { history: [{ id: 'hist-1', method: 'GET', name: 'List Users', url: 'https://api.staging.example.com/v1/users?page=1', status: '200', time: '142 ms', at: '今天 14:21:08' }, { id: 'hist-2', method: 'POST', name: 'Create Order', url: 'https://api.staging.example.com/v1/orders', status: '201', time: '310 ms', at: '今天 13:55:41' }, { id: 'hist-3', method: 'POST', name: 'Login', url: 'https://api.staging.example.com/v1/auth/login', status: '200', time: '98 ms', at: '今天 11:02:17' }, { id: 'hist-4', method: 'GET', name: 'Get Invoice', url: 'https://api.staging.example.com/v1/billing/invoices/inv_88', status: '404', time: '67 ms', at: '昨天 19:44:03' }, { id: 'hist-5', method: 'PATCH', name: 'Update User', url: 'https://api.staging.example.com/v1/users/u_1001', status: '200', time: '188 ms', at: '昨天 16:12:50' }, { id: 'hist-6', method: 'DELETE', name: 'Revoke Token', url: 'https://api.staging.example.com/v1/auth/token', status: '204', time: '54 ms', at: '08-08 21:06:22' }] } },
  template: /*html*/ `<WfAppShell><WfColumn id="history-page" class="history__page" :gap="16" :style="{ padding: '24px' }"><WfPageHeader id="history-header" title-id="history-title" class="history__header" title="历史记录" subtitle="本机最近发送的请求，可重新打开到编辑器"><template #actions><WfRow class="history__header-actions" :gap="8"><WfButton class="history__action-clear">清空历史</WfButton><WfButton class="history__action-workspace" to="workspace">返回工作区</WfButton></WfRow></template></WfPageHeader><WfColumn id="history-list" class="history__list" :gap="10"><WfCard v-for="item in history" :key="item.id" class="history__item" :data-wf-key="item.id" to="request-editor" :style="{ padding: '12px' }"><WfRow class="history__item-row" align-items="center" :gap="12"><WfBadge class="history__item-method">{{ item.method }}</WfBadge><WfColumn class="history__item-copy" :gap="2" :style="{ flex: 1, minWidth: 0 }"><strong class="history__item-name">{{ item.name }}</strong><WfText class="history__item-url" :style="{ fontSize: '12px' }">{{ item.url }}</WfText><WfText class="history__item-at" :style="{ fontSize: '12px', color: 'var(--wf-600)' }">{{ item.at }}</WfText></WfColumn><WfBadge class="history__item-status">{{ item.status }}</WfBadge><WfBadge class="history__item-time">{{ item.time }}</WfBadge><WfButton class="history__item-open" to="request-editor">打开</WfButton></WfRow></WfCard></WfColumn></WfColumn></WfAppShell>`,
}))
