/**
 * @wireframe-skill multi-screen-wireframe@2.1.0
 * 创建基于 v2.0.0
 * 修改基于 v2.1.0
 */
WireframeVue.defineScreen('request-editor', ({ ref }) => ({
  setup() {
    return {
      tab: ref('params'), respTab: ref('body'), method: ref('GET'), environment: ref('Staging'), url: ref('{{baseUrl}}/v1/users'), authType: ref('Bearer Token'), token: ref('{{token}}'), requestBody: ref('{\n  "note": "GET 请求通常无 Body，此处仅示意编辑区"\n}'),
      requestTabs: [{ id: 'params', label: 'Params' }, { id: 'headers', label: 'Headers' }, { id: 'body', label: 'Body' }, { id: 'auth', label: 'Authorization' }],
      responseTabs: [{ id: 'body', label: 'Body' }, { id: 'headers', label: 'Headers' }, { id: 'cookies', label: 'Cookies' }],
      columns: [{ key: 'key', label: 'Key' }, { key: 'value', label: 'Value' }, { key: 'desc', label: 'Description' }],
      params: [{ id: 'p-page', key: 'page', value: '1', desc: '页码' }, { id: 'p-size', key: 'size', value: '20', desc: '每页条数' }, { id: 'p-q', key: 'q', value: 'alice', desc: '关键字搜索' }, { id: 'p-status', key: 'status', value: 'active', desc: '用户状态' }],
      headers: [{ id: 'h-auth', key: 'Authorization', value: 'Bearer {{token}}', desc: '访问令牌' }, { id: 'h-accept', key: 'Accept', value: 'application/json', desc: '' }, { id: 'h-trace', key: 'X-Request-Id', value: '{{$guid}}', desc: '链路追踪' }, { id: 'h-client', key: 'X-Client', value: 'api-client-demo', desc: '' }],
      responseColumns: [{ key: 'key', label: 'Header' }, { key: 'value', label: 'Value' }],
      responseHeaders: [{ id: 'rh-ct', key: 'content-type', value: 'application/json; charset=utf-8' }, { id: 'rh-cache', key: 'cache-control', value: 'no-store' }, { id: 'rh-req', key: 'x-request-id', value: 'req_8f3a2c' }],
      responseJson: '{\n  "data": [\n    { "id": "u_1001", "name": "Alice", "role": "admin" },\n    { "id": "u_1002", "name": "Bob", "role": "editor" },\n    { "id": "u_1003", "name": "Carol", "role": "viewer" }\n  ],\n  "page": 1,\n  "total": 128\n}',
    }
  },
  template: /*html*/ `<WfAppShell><WfColumn id="request-editor-page" class="request-editor__page" :gap="0" :style="{ height: '100%' }"><WfColumn class="request-editor__top" :gap="12" :style="{ padding: '16px 24px 12px', borderBottom: '1px solid var(--wf-300)' }"><WfPageHeader id="request-editor-header" title-id="request-editor-title" class="request-editor__header" title="List Users" subtitle="User API / Users"><template #actions><WfRow class="request-editor__header-actions" :gap="8"><WfButton class="request-editor__action-collection" to="collection">返回 Collection</WfButton><WfButton class="request-editor__action-save" to="collection">Save</WfButton></WfRow></template></WfPageHeader>
    <WfRow id="request-editor-urlbar" class="request-editor__urlbar" :gap="8" align-items="center"><WfSelect v-model="method" class="request-editor__method" :style="{ width: '110px' }"><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option></WfSelect><WfTextInput id="request-editor-url" v-model="url" class="request-editor__url" :style="{ flex: 1 }" /><WfSelect v-model="environment" class="request-editor__env" :style="{ width: '140px' }"><option>Staging</option><option>Production</option><option>Local</option></WfSelect><WfButton id="request-editor-send" class="request-editor__send" variant="primary">Send</WfButton></WfRow>
    <WfTabs id="request-editor-tabs" v-model:active-id="tab" class="request-editor__tabs" :items="requestTabs" /><WfDataTable v-if="tab === 'params'" id="request-editor-params" class="request-editor__params" :columns="columns" :rows="params" /><WfDataTable v-else-if="tab === 'headers'" id="request-editor-headers" class="request-editor__headers" :columns="columns" :rows="headers" /><WfCard v-else-if="tab === 'body'" id="request-editor-body" class="request-editor__body" :style="{ padding: '12px' }"><WfRow class="request-editor__body-toolbar" :gap="8" :style="{ marginBottom: '8px' }"><WfBadge class="request-editor__body-type">raw</WfBadge><WfBadge class="request-editor__body-format">JSON</WfBadge></WfRow><WfTextArea v-model="requestBody" class="request-editor__body-input" :rows="6" /></WfCard><WfCard v-else id="request-editor-auth" class="request-editor__auth" :style="{ padding: '14px' }"><WfColumn class="request-editor__auth-fields" :gap="10"><WfRow class="request-editor__auth-row" :gap="12" align-items="center"><WfText class="request-editor__auth-label" :style="{ width: '80px' }">Type</WfText><WfSelect v-model="authType" class="request-editor__auth-type" :style="{ width: '200px' }"><option>Bearer Token</option><option>API Key</option><option>Basic Auth</option><option>No Auth</option></WfSelect></WfRow><WfRow class="request-editor__auth-row" :gap="12" align-items="center"><WfText class="request-editor__auth-label" :style="{ width: '80px' }">Token</WfText><WfTextInput v-model="token" class="request-editor__auth-token" :style="{ flex: 1 }" /></WfRow></WfColumn></WfCard></WfColumn>
    <WfColumn id="request-editor-response" class="request-editor__response" :gap="10" :style="{ flex: 1, padding: '24px', background: 'var(--wf-50)', minHeight: '280px' }"><WfRow class="request-editor__response-head" align-items="center" justify-content="space-between"><WfHeading class="request-editor__response-title" :level="3">Response</WfHeading><WfRow class="request-editor__response-meta" :gap="8"><WfBadge class="request-editor__status">200 OK</WfBadge><WfBadge class="request-editor__time">142 ms</WfBadge><WfBadge class="request-editor__size">3.2 KB</WfBadge></WfRow></WfRow><WfTabs id="request-editor-response-tabs" v-model:active-id="respTab" class="request-editor__response-tabs" :items="responseTabs" /><WfCard v-if="respTab === 'body'" id="request-editor-response-body" class="request-editor__response-body" :style="{ padding: '12px' }"><pre class="request-editor__response-json" :style="{ margin: 0, fontSize: '12px', whiteSpace: 'pre-wrap', fontFamily: 'ui-monospace, monospace' }">{{ responseJson }}</pre></WfCard><WfDataTable v-else-if="respTab === 'headers'" id="request-editor-response-headers" class="request-editor__response-headers" :columns="responseColumns" :rows="responseHeaders" /><WfCard v-else id="request-editor-cookies" class="request-editor__cookies" :style="{ padding: '16px' }"><WfText class="request-editor__cookies-empty">本次响应未设置 Cookie</WfText></WfCard></WfColumn>
  </WfColumn></WfAppShell>`,
}))
