/**
 * @wireframe-skill multi-screen-wireframe@2.1.0
 * 创建基于 v2.0.0
 * 修改基于 v2.1.0
 */
WireframeVue.defineScreen('settings', ({ ref }) => ({
  setup() { return { ssl: ref(true), followRedirect: ref(true), proxy: ref(false), timeout: ref('15000'), host: ref('127.0.0.1'), port: ref('7890') } },
  template: /*html*/ `<WfAppShell><WfColumn id="settings-page" class="settings__page" :gap="16" :style="{ padding: '24px' }"><WfPageHeader id="settings-header" title-id="settings-title" class="settings__header" title="设置" subtitle="通用偏好、代理与证书（线框示意）"><template #actions><WfButton class="settings__action-workspace" to="workspace">返回工作区</WfButton></template></WfPageHeader>
    <WfCard id="settings-general" class="settings__section" :style="{ padding: '16px' }"><WfColumn class="settings__section-body" :gap="14"><WfText class="settings__section-title" :style="{ fontWeight: 600 }">通用</WfText><WfFormField class="settings__field" label="默认超时（ms）" for="settings-timeout"><WfTextInput id="settings-timeout" v-model="timeout" class="settings__timeout" /></WfFormField><WfRow class="settings__toggle-row" align-items="center" justify-content="space-between"><WfText class="settings__toggle-label">自动跟随重定向</WfText><WfToggle id="settings-redirect" v-model:checked="followRedirect" class="settings__redirect" /></WfRow><WfRow class="settings__toggle-row" align-items="center" justify-content="space-between"><WfText class="settings__toggle-label">校验证书（SSL）</WfText><WfToggle id="settings-ssl" v-model:checked="ssl" class="settings__ssl" /></WfRow></WfColumn></WfCard>
    <WfCard id="settings-proxy" class="settings__section" :style="{ padding: '16px' }"><WfColumn class="settings__section-body" :gap="14"><WfRow class="settings__proxy-head" align-items="center" justify-content="space-between"><WfText class="settings__section-title" :style="{ fontWeight: 600 }">代理</WfText><WfToggle id="settings-proxy-toggle" v-model:checked="proxy" class="settings__proxy-toggle" :label="proxy ? '开启' : '关闭'" /></WfRow><WfFormField class="settings__field" label="Host" for="settings-proxy-host"><WfTextInput id="settings-proxy-host" v-model="host" class="settings__proxy-host" /></WfFormField><WfFormField class="settings__field" label="Port" for="settings-proxy-port"><WfTextInput id="settings-proxy-port" v-model="port" class="settings__proxy-port" /></WfFormField></WfColumn></WfCard>
    <WfCard id="settings-certs" class="settings__section" :style="{ padding: '16px' }"><WfColumn class="settings__section-body" :gap="10"><WfText class="settings__section-title" :style="{ fontWeight: 600 }">证书</WfText><WfText class="settings__certs-empty" :style="{ fontSize: '13px' }">尚未添加客户端证书。生产环境可在此挂载 .pem / .p12。</WfText><WfButton class="settings__certs-add">添加证书</WfButton></WfColumn></WfCard>
  </WfColumn></WfAppShell>`,
}))
