/**
 * @wireframe-skill multi-screen-wireframe@2.1.0
 * 创建基于 v2.0.0
 * 修改基于 v2.1.0
 */
WireframeVue.defineScreen('budget', ({ ref }) => ({
  setup() { return { inviteOpen: ref(false), invitee: ref(''), columns: [{ key: 'item', label: '项目' }, { key: 'owner', label: '承担' }, { key: 'amount', label: '金额' }], costs: [{ id: 'cost-transit', item: '市内交通', owner: '共同', amount: '48' }, { id: 'cost-ticket', item: '展厅门票', owner: '林晓野', amount: '80' }, { id: 'cost-lunch', item: '午餐', owner: '共同', amount: '180' }, { id: 'cost-market', item: '市集预留', owner: '个人', amount: '120' }], members: [{ id: 'member-lin', name: '林晓野' }, { id: 'member-chen', name: '陈榆' }, { id: 'member-zhou', name: '周岸' }] } },
  template: /*html*/ `<WfMobileLayout><WfColumn id="budget-page" :gap="18" class="weekend-page budget__page"><WfPageHeader id="budget-header" title-id="budget-title" class="budget__header" title="预算与同行人" subtitle="为行程预留费用并邀请伙伴"><template #actions><WfButton class="budget__back" to="trip-confirm">返回</WfButton></template></WfPageHeader><WfCard id="budget-summary" class="budget__summary"><WfColumn class="budget__summary-body" :gap="6"><WfText class="budget__summary-label">预计总费用</WfText><strong class="budget__summary-value">428 元</strong><WfText class="budget__summary-note">按 3 位同行人计算，人均约 143 元</WfText></WfColumn></WfCard><WfDataTable id="budget-table" class="budget__table" :columns="columns" :rows="costs" /><WfColumn id="budget-members" class="budget__members" :gap="12"><WfRow class="budget__members-heading" align-items="center" justify-content="space-between"><WfText class="budget__members-label">同行人</WfText><WfButton id="budget-invite-action" class="budget__invite-action" @click="inviteOpen = true">邀请</WfButton></WfRow><WfRow class="budget__member-stack" :gap="14"><WfColumn v-for="member in members" :key="member.id" class="budget__member" :data-wf-key="member.id" :gap="5" align-items="center"><WfAvatar class="budget__member-avatar" :label="member.name" /><WfText class="budget__member-name">{{ member.name }}</WfText></WfColumn></WfRow></WfColumn><WfButton id="budget-done" class="budget__done" variant="primary" to="trip-confirm">保存预算</WfButton><WfModal id="budget-invite-modal" class="budget__invite-modal" :open="inviteOpen" title="邀请同行人" @close="inviteOpen = false"><WfFormField class="budget__invite-field" label="手机号或用户名" for="budget-invite-input"><WfTextInput id="budget-invite-input" v-model="invitee" class="budget__invite-input" placeholder="输入同行人信息" /></WfFormField><template #actions><WfButton class="budget__invite-submit" variant="primary" @click="inviteOpen = false">发送邀请</WfButton></template></WfModal></WfColumn></WfMobileLayout>`,
}))
