/**
 * @wireframe-skill multi-screen-wireframe@2.1.0
 * 创建基于 v2.0.0
 * 修改基于 v2.1.0
 */
WireframeVue.defineScreen('discover', () => ({
  setup() { return { routes: [{ id: 'route-canal', title: '运河边的一天', meta: '步行 8.6 km · 6 小时', note: '旧仓库、桥下市集与傍晚河岸' }, { id: 'route-hills', title: '城北轻徒步', meta: '徒步 11 km · 7 小时', note: '林间缓坡、观景台与山脚小馆' }, { id: 'route-lanes', title: '老街慢游', meta: '步行 5.2 km · 4 小时', note: '巷口早餐、旧书店与社区花园' }, { id: 'route-lake', title: '环湖骑行半日', meta: '骑行 18 km · 5 小时', note: '湿地栈道、堤岸与日落平台' }, { id: 'route-museum', title: '雨天博物馆线', meta: '公交 4 站 · 6 小时', note: '三个展馆与一间安静咖啡馆' }, { id: 'route-night', title: '夜色建筑散步', meta: '步行 6.4 km · 3 小时', note: '广场、剧院与江边灯光带' }] } },
  template: /*html*/ `<WfMobileLayout><WfColumn id="discover-page" :gap="18" class="weekend-page discover__page"><WfPageHeader id="discover-header" title-id="discover-title" subtitle-id="discover-subtitle" class="discover__header" title="这个周末，去哪走走" subtitle="为你挑了几条不用赶时间的城市路线"><template #actions><WfButton id="discover-map-action" class="discover__map-action" to="explore-map">地图</WfButton></template></WfPageHeader>
    <WfCard id="discover-featured" class="weekend-route-card discover__featured" to="route-detail"><WfImagePlaceholder class="discover__featured-image" :height="176" :border-radius="0" /><WfColumn class="weekend-route-card__body discover__featured-body" :gap="10"><WfRow class="weekend-chip-row discover__featured-badges" :gap="8"><WfBadge class="discover__featured-badge">本周推荐</WfBadge><WfBadge class="discover__featured-badge">适合初次到访</WfBadge></WfRow><WfHeading class="discover__featured-title" :level="2">运河边的一天</WfHeading><WfText class="discover__featured-copy">从旧仓库出发，沿水岸走到桥下市集，在日落前抵达河湾平台。</WfText><WfRow class="weekend-card-meta discover__featured-meta" :gap="12"><WfText class="discover__featured-meta-item">8.6 km</WfText><WfText class="discover__featured-meta-item">约 6 小时</WfText><WfText class="discover__featured-meta-item">轻松</WfText></WfRow></WfColumn></WfCard>
    <WfHeading id="discover-routes-title" class="weekend-section-heading discover__routes-title" :level="2">更多路线</WfHeading><WfGrid id="discover-routes" class="discover__routes" :columns="1" :gap="14"><WfCard v-for="(route, index) in routes" :key="route.id" class="weekend-route-card discover__route-card" :data-wf-key="route.id" to="route-detail"><WfImagePlaceholder class="discover__route-image" :height="index % 2 === 0 ? 116 : 136" :border-radius="0" /><WfColumn class="weekend-route-card__body discover__route-body" :gap="7"><WfHeading class="discover__route-title" :level="3">{{ route.title }}</WfHeading><WfText class="discover__route-meta">{{ route.meta }}</WfText><WfText class="discover__route-note">{{ route.note }}</WfText></WfColumn></WfCard></WfGrid>
  </WfColumn></WfMobileLayout>`,
}))
