/**
 * @wireframe-skill multi-screen-wireframe@2.1.0
 * 创建基于 v2.0.0
 * 修改基于 v2.1.0
 */
WireframeVue.defineScreen('route-detail', ({ ref }) => ({
  setup() { return { tab: ref('overview'), breadcrumbs: [{ label: '发现', to: 'discover' }, { label: '运河边的一天' }], tabs: [{ id: 'overview', label: '路线概览' }, { id: 'notes', label: '出发须知' }], stops: [{ id: 'stop-warehouse', title: '旧仓库展厅', subtitle: '09:30 · 建议停留 60 分钟' }, { id: 'stop-bridge', title: '桥下周末市集', subtitle: '11:00 · 建议停留 90 分钟' }, { id: 'stop-lane', title: '水岸小巷', subtitle: '13:30 · 午餐与街区散步' }, { id: 'stop-garden', title: '社区花园', subtitle: '15:20 · 建议停留 45 分钟' }, { id: 'stop-bend', title: '河湾日落平台', subtitle: '17:10 · 路线终点' }] } },
  template: /*html*/ `<WfMobileLayout><WfColumn id="route-detail-page" :gap="18" class="weekend-page route-detail__page"><WfBreadcrumbs id="route-detail-breadcrumbs" class="route-detail__breadcrumbs" :items="breadcrumbs" /><WfImagePlaceholder id="route-detail-hero" class="route-detail__hero" :height="224" :border-radius="0" /><WfColumn id="route-detail-summary" class="route-detail__summary" :gap="10"><WfRow class="weekend-chip-row route-detail__badges" :gap="8"><WfBadge class="route-detail__badge">城市漫步</WfBadge><WfBadge class="route-detail__badge">轻松</WfBadge><WfBadge class="route-detail__badge">可带宠物</WfBadge></WfRow><WfHeading id="route-detail-title" class="route-detail__title" :level="1">运河边的一天</WfHeading><WfText class="route-detail__intro">一条从工业遗存走向生活街区的水岸路线。上午看展，中午逛市集，傍晚在河湾等日落。</WfText></WfColumn><WfGrid id="route-detail-facts" class="route-detail__facts" :columns="3" :gap="8"><WfCard class="route-detail__fact"><span class="route-detail__fact-value">8.6 km</span><span class="route-detail__fact-label">总路程</span></WfCard><WfCard class="route-detail__fact"><span class="route-detail__fact-value">6 小时</span><span class="route-detail__fact-label">建议时长</span></WfCard><WfCard class="route-detail__fact"><span class="route-detail__fact-value">5 站</span><span class="route-detail__fact-label">路线节点</span></WfCard></WfGrid><WfTabs id="route-detail-tabs" v-model:active-id="tab" class="route-detail__tabs" :items="tabs" /><WfColumn v-if="tab === 'overview'" id="route-detail-stops" class="route-detail__stops" :gap="0"><WfCell v-for="(stop, index) in stops" :key="stop.id" class="route-detail__stop" :data-wf-key="stop.id" :title="(index + 1) + '. ' + stop.title" :subtitle="stop.subtitle" :value="String(index + 1)" /></WfColumn><WfCard v-else id="route-detail-notes" class="route-detail__notes"><WfColumn class="route-detail__notes-body" :gap="10"><WfText class="route-detail__note">沿途大部分路段有树荫，河湾区域下午日照较强。</WfText><WfText class="route-detail__note">旧仓库周一闭馆，周末建议提前预约入场时段。</WfText><WfText class="route-detail__note">路线终点距离地铁站约 900 米，也可乘坐社区接驳车。</WfText></WfColumn></WfCard><WfCard id="route-detail-guide" class="route-detail__guide"><WfColumn class="route-detail__guide-body" :gap="8"><WfHeading class="route-detail__guide-title" :level="3">路线策划人</WfHeading><WfText class="route-detail__guide-copy">林屿 · 城市步行记录者，已发布 18 条水岸路线。</WfText></WfColumn></WfCard><WfColumn id="route-detail-actions" class="route-detail__actions" :gap="10"><WfButton id="route-detail-itinerary-action" class="route-detail__itinerary-action" to="itinerary">查看完整日程</WfButton><WfButton id="route-detail-create-action" class="route-detail__create-action" variant="primary" to="trip-create">用这条路线创建行程</WfButton></WfColumn></WfColumn></WfMobileLayout>`,
}))
