/**
 * @wireframe-skill multi-screen-wireframe@2.1.0
 * 创建基于 v2.0.0
 * 修改基于 v2.1.0
 */
WireframeVue.defineScreen('trips', ({ ref }) => ({
  setup() { return { tab: ref('upcoming'), tabs: [{ id: 'upcoming', label: '待出发' }, { id: 'completed', label: '已完成' }, { id: 'saved', label: '收藏' }], trips: [{ id: 'trip-canal', title: '周六运河散步', date: '8 月 15 日', status: '待出发', detail: '3 人 · 5 个地点' }, { id: 'trip-lake', title: '环湖骑行半日', date: '8 月 22 日', status: '规划中', detail: '2 人 · 4 个地点' }, { id: 'trip-museum', title: '雨天博物馆线', date: '9 月 5 日', status: '待确认', detail: '4 人 · 3 个场馆' }, { id: 'trip-hills', title: '城北轻徒步', date: '9 月 12 日', status: '规划中', detail: '3 人 · 6 个地点' }], completed: [{ id: 'trip-old-street', title: '老街慢游', date: '7 月 18 日 · 已完成' }, { id: 'trip-night-walk', title: '夜色建筑散步', date: '6 月 27 日 · 已完成' }, { id: 'trip-riverside', title: '南岸旧码头', date: '5 月 16 日 · 已完成' }] } },
  template: /*html*/ `<WfMobileLayout><WfColumn id="trips-page" :gap="18" class="weekend-page trips__page"><WfPageHeader id="trips-header" title-id="trips-title" class="trips__header" title="我的行程" subtitle="计划、同行信息与旅行记录"><template #actions><WfButton id="trips-create-action" class="trips__create-action" to="trip-create">新建</WfButton></template></WfPageHeader><WfTabs id="trips-tabs" v-model:active-id="tab" class="trips__tabs" :items="tabs" /><WfColumn v-if="tab === 'upcoming'" id="trips-upcoming" class="trips__list" :gap="12"><WfCard v-for="trip in trips" :key="trip.id" class="trips__card" :data-wf-key="trip.id" to="route-detail"><WfColumn class="trips__card-body" :gap="9"><WfRow class="trips__card-heading" align-items="center" justify-content="space-between" :gap="8"><WfHeading class="trips__card-title" :level="3">{{ trip.title }}</WfHeading><WfBadge class="trips__card-status">{{ trip.status }}</WfBadge></WfRow><WfText class="trips__card-date">{{ trip.date }}</WfText><WfRow class="trips__status-row" :gap="10"><WfText class="trips__card-detail">{{ trip.detail }}</WfText><WfText class="trips__card-reminder">提醒已开启</WfText></WfRow></WfColumn></WfCard></WfColumn><WfColumn v-else-if="tab === 'completed'" id="trips-completed" class="trips__completed" :gap="12"><WfCard v-for="trip in completed" :key="trip.id" class="trips__card" :data-wf-key="trip.id" to="route-detail"><WfColumn class="trips__card-body" :gap="8"><WfHeading class="trips__card-title" :level="3">{{ trip.title }}</WfHeading><WfText class="trips__card-date">{{ trip.date }}</WfText></WfColumn></WfCard></WfColumn><WfEmptyState v-else id="trips-saved-empty" class="trips__empty" title="还没有收藏路线" description="在路线详情中收藏，稍后再决定什么时候出发。"><template #action><WfButton class="trips__empty-action" to="discover">去发现路线</WfButton></template></WfEmptyState></WfColumn></WfMobileLayout>`,
}))
