/**
 * @wireframe-skill multi-screen-wireframe@2.1.0
 * 创建基于 v2.0.0
 * 修改基于 v2.1.0
 */
WireframeVue.defineScreen('trip-create', ({ ref }) => ({
  setup() { return { name: ref('周六运河散步'), date: ref('2026-08-15'), start: ref('metro'), note: ref(''), easy: ref(true), standard: ref(false), compact: ref(false), accessible: ref(false), noBooking: ref(true), reminder: ref(true), steps: [{ id: 'basic', label: '基本信息' }, { id: 'budget', label: '预算' }, { id: 'confirm', label: '确认' }] } },
  template: /*html*/ `<WfMobileLayout><WfColumn id="trip-create-page" :gap="17" class="weekend-page trip-create__page"><WfPageHeader id="trip-create-header" title-id="trip-create-title" class="trip-create__header" title="创建行程" subtitle="先确定时间与同行方式"><template #actions><WfButton class="trip-create__cancel" to="route-detail">取消</WfButton></template></WfPageHeader><WfSteps id="trip-create-steps" class="trip-create__steps" :current="0" :items="steps" /><WfFormField class="trip-create__name-field" label="行程名称" for="trip-create-name"><WfTextInput id="trip-create-name" v-model="name" class="trip-create__name-input" /></WfFormField><WfFormField class="trip-create__date-field" label="出发日期" for="trip-create-date" hint="建议选择天气稳定的日期"><WfTextInput id="trip-create-date" v-model="date" class="trip-create__date-input" /></WfFormField><WfFormField class="trip-create__start-field" label="集合地点" for="trip-create-start"><WfSelect id="trip-create-start" v-model="start" class="trip-create__start-select"><option class="trip-create__start-option" value="metro">运河路地铁站 3 号口</option><option class="trip-create__start-option" value="warehouse">旧仓库正门</option><option class="trip-create__start-option" value="custom">自定义地点</option></WfSelect></WfFormField><WfColumn id="trip-create-pace" class="trip-create__pace" :gap="9"><span class="trip-create__group-label">行程节奏</span><WfRow class="trip-create__pace-options" :gap="12"><WfRadio v-model="easy" class="trip-create__pace-option" name="pace" label="轻松" /><WfRadio v-model="standard" class="trip-create__pace-option" name="pace" label="标准" /><WfRadio v-model="compact" class="trip-create__pace-option" name="pace" label="紧凑" /></WfRow></WfColumn><WfFormField class="trip-create__note-field" label="同行备注" for="trip-create-note"><WfTextArea id="trip-create-note" v-model="note" class="trip-create__note-input" placeholder="例如：有儿童同行，希望减少楼梯路段" /></WfFormField><WfColumn id="trip-create-preferences" class="trip-create__preferences" :gap="10"><WfCheckbox v-model="accessible" class="trip-create__preference" label="优先安排无障碍路线" /><WfCheckbox v-model="noBooking" class="trip-create__preference" label="避开需要预约的地点" /><WfToggle id="trip-create-reminder" v-model:checked="reminder" class="trip-create__reminder" label="出发前一天提醒" /></WfColumn><WfButton id="trip-create-next" class="trip-create__next" variant="primary" to="budget">下一步：预算与同行人</WfButton></WfColumn></WfMobileLayout>`,
}))
